name: AutoUpgrade

on:
  schedule:
    - cron: 0 0 * * * 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: create pull request
      run: |
        # check target repository
        test "imas/homebrew-rdflint" == "${{ github.repository }}" || exit 0

        # check latest version
        CURRENT_VERSION=$(cat rdflint.rb | grep ^RDFLINT_VERSION | sed -e "s/^RDFLINT_VERSION='\(.*\)'$/\1/")
        LATEST_VERSION=$(curl https://jitpack.io/api/builds/com.github.imas/rdflint/latestOk | grep version | sed -e "s/^.*:.*\"\(.*\)\"$/\1/")
        git fetch origin && git branch -a | grep rdflint-$LATEST_VERSION && exit 0
        test "$CURRENT_VERSION" == "$LATEST_VERSION" && exit 0

        # get latest jar
        wget https://jitpack.io/com/github/imas/rdflint/$LATEST_VERSION/rdflint-$LATEST_VERSION.jar
        SHA256=$(shasum -a 256 rdflint-$LATEST_VERSION.jar | awk '{print $1}')

        # edit rdflint.rb
        cat rdflint.rb | sed -e "s/^RDFLINT_VERSION='\(.*\)'$/RDFLINT_VERSION='$LATEST_VERSION'/" \
          | sed -e "s/sha256 *\"\(.*\)\"/sha256 \"$SHA256\"/" > rdflint.rb.new
        cp rdflint.rb.new rdflint.rb
        rm rdflint.rb.new

        # create commit
        git config --global user.email "bot@example.com"
        git config --global user.name "bot"          
        git checkout -b rdflint-$LATEST_VERSION
        git commit rdflint.rb -m "rdflint-$LATEST_VERSION"
        git push origin rdflint-$LATEST_VERSION

        # create pull request
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pulls \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "upgrade rdflint $LATEST_VERSION",
            "body": "Automated pull request for upgrade rdflint $LATEST_VERSION.",
            "head": "imas:rdflint-$LATEST_VERSION",
            "base": "master"
          }'
